import type { Job, Applicant } from "./types";

export const mockJobs: Job[] = [
  {
    id: "1",
    title: "Senior Frontend Engineer",
    company: "Innovate Inc.",
    description:
      "We are looking for an experienced frontend engineer to lead our web development efforts.",
    responsibilities:
      "- Build and maintain user-facing features\n- Collaborate with designers and product managers\n- Mentor junior developers\n- Ensure code quality through reviews",
    requirements:
      "- 5+ years of React experience\n- Strong TypeScript skills\n- Experience with Next.js\n- Excellent communication skills",
    workArrangement: "remote",
    salaryRange: "$120,000 - $150,000",
    deadline: "2024-02-15",
    location: "San Francisco, CA",
    status: "active",
    createdAt: "2023-10-12",
    applicantCount: 125,
  },
  {
    id: "2",
    title: "Product Designer",
    company: "Creative Solutions",
    description:
      "Join our design team to create beautiful and intuitive user experiences.",
    responsibilities:
      "- Design user interfaces\n- Conduct user research\n- Create prototypes\n- Collaborate with developers",
    requirements:
      "- 3+ years of product design experience\n- Proficiency in Figma\n- Strong portfolio\n- UX research skills",
    workArrangement: "hybrid",
    salaryRange: "$90,000 - $120,000",
    deadline: "2024-01-30",
    location: "New York, NY",
    status: "active",
    createdAt: "2023-09-28",
    applicantCount: 78,
  },
  {
    id: "3",
    title: "Lead Backend Developer (Python)",
    company: "DataForge",
    description:
      "Lead our backend team in building scalable data processing systems.",
    responsibilities:
      "- Architect backend systems\n- Lead a team of 5 developers\n- Design APIs\n- Optimize database performance",
    requirements:
      "- 7+ years Python experience\n- Experience with Django/FastAPI\n- Strong database skills\n- Leadership experience",
    workArrangement: "onsite",
    salaryRange: "$140,000 - $180,000",
    deadline: "2024-02-28",
    location: "Austin, TX",
    status: "on-hold",
    createdAt: "2023-09-15",
    applicantCount: 210,
  },
  {
    id: "4",
    title: "Marketing Manager",
    company: "Innovate Inc.",
    description: "Drive our marketing strategy and brand growth.",
    responsibilities:
      "- Develop marketing strategies\n- Manage marketing budget\n- Lead campaigns\n- Analyze performance metrics",
    requirements:
      "- 5+ years marketing experience\n- B2B marketing background\n- Data-driven approach\n- Team management experience",
    workArrangement: "hybrid",
    salaryRange: "$100,000 - $130,000",
    deadline: "2023-12-31",
    location: "Chicago, IL",
    status: "closed",
    createdAt: "2023-08-30",
    applicantCount: 342,
  },
];

export const mockApplicants: Applicant[] = [
  {
    id: "1",
    jobId: "1",
    name: "Liam Johnson",
    email: "liam.j@example.com",
    phone: "+1 (555) 123-4567",
    avatar: "/placeholder.svg?height=80&width=80",
    resumeUrl: "#",
    resumeName: "Liam_Johnson_Resume.pdf",
    coverLetter:
      "I am excited to apply for the Senior Frontend Engineer position at Innovate Inc. With over 7 years of experience in frontend development, specializing in React and TypeScript, I believe I would be a valuable addition to your team. My recent work includes building scalable web applications for enterprise clients, implementing complex state management solutions, and mentoring junior developers. I am particularly drawn to Innovate Inc.'s commitment to innovation and would love to contribute to your mission.",
    seniorityLevel: "senior",
    aiScore: 92,
    aiScoreTrend: "up",
    status: "interviewing",
    statusUpdate: "Interview Scheduled",
    appliedAt: "2023-10-20",
    strengths: [
      "Expert in React & TypeScript",
      "7+ years in frontend development",
      "Strong portfolio of complex web apps",
      "Excellent communication skills",
    ],
    weaknesses: [
      "Limited experience with backend tech",
      "No direct team leadership experience",
    ],
  },
  {
    id: "2",
    jobId: "1",
    name: "Emma Watson",
    email: "emma.w@example.com",
    phone: "+1 (555) 234-5678",
    avatar: "/placeholder.svg?height=80&width=80",
    resumeUrl: "#",
    resumeName: "Emma_Watson_Resume.pdf",
    coverLetter:
      "As a passionate frontend developer with 5 years of experience, I am thrilled to apply for this role. I have extensive experience with React, Vue, and modern JavaScript frameworks.",
    seniorityLevel: "mid",
    aiScore: 88,
    aiScoreTrend: "up",
    status: "shortlisted",
    statusUpdate: "Shortlisted",
    appliedAt: "2023-10-22",
    strengths: [
      "Strong React and Vue experience",
      "Excellent problem-solving skills",
      "Great team collaboration",
    ],
    weaknesses: [
      "Less experience with TypeScript",
      "Limited Next.js experience",
    ],
  },
  {
    id: "3",
    jobId: "1",
    name: "Noah Miller",
    email: "noah.m@example.com",
    phone: "+1 (555) 345-6789",
    avatar: "/placeholder.svg?height=80&width=80",
    resumeUrl: "#",
    resumeName: "Noah_Miller_Resume.pdf",
    coverLetter:
      "I am writing to express my interest in the Senior Frontend Engineer position. I have 4 years of experience in web development.",
    seniorityLevel: "mid",
    aiScore: 75,
    aiScoreTrend: "stable",
    status: "applied",
    statusUpdate: "Applied on 2023-10-26",
    appliedAt: "2023-10-26",
    strengths: [
      "Good JavaScript fundamentals",
      "Quick learner",
      "Enthusiastic about new technologies",
    ],
    weaknesses: [
      "Limited senior-level experience",
      "Less exposure to large-scale projects",
      "Needs more TypeScript practice",
    ],
  },
  {
    id: "4",
    jobId: "1",
    name: "Olivia Davis",
    email: "olivia.d@example.com",
    phone: "+1 (555) 456-7890",
    avatar: "/placeholder.svg?height=80&width=80",
    resumeUrl: "#",
    resumeName: "Olivia_Davis_Resume.pdf",
    coverLetter:
      "I would like to apply for the frontend position at your company.",
    seniorityLevel: "junior",
    aiScore: 58,
    aiScoreTrend: "down",
    status: "rejected",
    statusUpdate: "Declined by AI filter",
    appliedAt: "2023-10-24",
    strengths: ["Basic React knowledge", "Good design sense"],
    weaknesses: [
      "Insufficient experience level",
      "Missing required TypeScript skills",
      "No Next.js experience",
      "Portfolio needs improvement",
    ],
  },
  {
    id: "5",
    jobId: "1",
    name: "Ethan Wilson",
    email: "ethan.w@example.com",
    phone: "+1 (555) 567-8901",
    avatar: "/placeholder.svg?height=80&width=80",
    resumeUrl: "#",
    resumeName: "Ethan_Wilson_Resume.pdf",
    coverLetter:
      "I am extremely excited about the opportunity to join Innovate Inc. as a Senior Frontend Engineer. With my 8 years of experience and deep expertise in React ecosystem, I am confident I can make significant contributions.",
    seniorityLevel: "senior",
    aiScore: 95,
    aiScoreTrend: "up",
    status: "hired",
    statusUpdate: "Hired on 2023-11-15",
    appliedAt: "2023-10-18",
    strengths: [
      "Expert-level React & TypeScript",
      "8 years of frontend experience",
      "Led teams of 5+ developers",
      "Open source contributor",
      "Excellent references",
    ],
    weaknesses: ["Salary expectations slightly high"],
  },
  {
    id: "6",
    jobId: "1",
    name: "Sophia Chen",
    email: "sophia.c@example.com",
    phone: "+1 (555) 678-9012",
    avatar: "/placeholder.svg?height=80&width=80",
    resumeUrl: "#",
    resumeName: "Sophia_Chen_Resume.pdf",
    coverLetter:
      "I am applying for the Senior Frontend Engineer role. I have 6 years of experience in building web applications.",
    seniorityLevel: "senior",
    aiScore: 85,
    aiScoreTrend: "up",
    status: "applied",
    statusUpdate: "Applied on 2023-10-28",
    appliedAt: "2023-10-28",
    strengths: [
      "Strong full-stack capabilities",
      "Experience with micro-frontends",
      "Good testing practices",
    ],
    weaknesses: ["Prefers backend work", "Limited mentoring experience"],
  },
];
